#!/bin/bash

	#Realiza un script con cron que escriba cada 10 minutos los siguientes datos en el
#fichero /var/log/historial.txt
#A continuación se muestra un ejemplo del contenido del fichero
#13:37:44 up 20 days, 59 min, 1 user, load average: 0,00, 0,00, 0,00 USER TTY FROM
#LOGIN@ IDLE JCPU PCPU WHAT root pts/0 36.pool85-57-33. 13:37 0.00s 0.00s 0.00s w

	w >> /var/log/historial.txt

	# Y para hacer que se ejecute cada 10 minutos modificamos
	# el crontab y añadir la siguiente linea 

	# */10 * * * * ~/script6_UT8P4.sh